FROM apache/spark:4.0.0-python3
USER root
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.0/hadoop-aws-3.4.0.jar /opt/spark/jars/
# ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar /opt/spark/jars/
ADD https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.23.19/bundle-2.23.19.jar /opt/spark/jars/
WORKDIR $SPARK_HOME
ENTRYPOINT sbin/start-worker.sh $SPARK_MASTER_URL