services:
  # minIO
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
        sleep 2;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb -p local/inventory || true;
        mc cp /seed/inventory_raw.csv local/inventory/inventory_raw.csv;
        exit 0
      "
    volumes:
      - ./inputs:/seed:ro

  # Spark master
  spark-master:
    build: spark/
    ports:
      - 7077:7077
      - 7070:7070
    container_name: spark-master
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 7070
      SPARK_DAEMON_MEMORY: 200M
      SPARK_NO_DAEMONIZE: 1
    volumes:
      - ./inputs:/data:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

  # Spark worker
  spark-worker-1:
    build: spark/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_NO_DAEMONIZE: 1
    volumes:
      - ./inputs:/data:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # Deepseek-powered FastAPI server for transforming owner class
  transformation-server:
    build: src/
    ports:
      - 8000:8000
    container_name: transformation-server
    volumes:
      - ./src/app:/opt/src/app
      - ./tmp:/opt/tmp

  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 5
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.10.2
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "devsecret"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./inputs:/opt/airflow/inputs
      - ./tmp:/opt/airflow/tmp
      - ./outputs:/opt/airflow/outputs

  airflow-scheduler:
    image: apache/airflow:2.10.2
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    command: ["airflow", "scheduler"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "devsecret"
      # match your local timezone for UI/logs
      AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Vancouver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./inputs:/opt/airflow/inputs
      - ./tmp:/opt/airflow/tmp
      - ./outputs:/opt/airflow/outputs

  airflow-webserver:
    image: apache/airflow:2.10.2
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    command: ["airflow", "webserver"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "devsecret"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Vancouver"
    ports:
      - "8080:8080" # open Airflow UI on localhost:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./inputs:/opt/airflow/inputs
      - ./tmp:/opt/airflow/tmp
      - ./outputs:/opt/airflow/outputs
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-triggerer:
    image: apache/airflow:2.10.2
    container_name: airflow_triggerer
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped
    command: ["airflow", "triggerer"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "devsecret"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Vancouver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
      - ./inputs:/opt/airflow/inputs
      - ./tmp:/opt/airflow/tmp
      - ./outputs:/opt/airflow/outputs


volumes:
  postgres_data:
  minio-data:
