FROM apache/airflow:2.10.2-python3.10
USER root

# 1) Install Temurin 17 JDK from Adoptium
RUN set -eux; \
    apt-get update; \
    apt-get install -y wget gnupg; \
    mkdir -p /etc/apt/keyrings; \
    wget -O- https://packages.adoptium.net/artifactory/api/gpg/key/public \
      | gpg --dearmor > /etc/apt/keyrings/adoptium.gpg; \
    . /etc/os-release; \
    echo "deb [signed-by=/etc/apt/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb ${VERSION_CODENAME} main" \
      > /etc/apt/sources.list.d/adoptium.list; \
    apt-get update; \
    apt-get install -y temurin-17-jdk; \
    rm -rf /var/lib/apt/lists/*
    
# 2) Set JAVA_HOME to where Temurin 17 installs
ENV JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-arm64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Install Spark (match your Spark cluster version!)
RUN curl -L "https://archive.apache.org/dist/spark/spark-4.0.0/spark-4.0.0-bin-hadoop3.tgz" \
    | tar -xz -C /opt/ \
 && mv /opt/spark-4.0.0-bin-hadoop3 /opt/spark

ENV SPARK_HOME=/opt/spark
ENV PATH="$SPARK_HOME/bin:$PATH"


USER airflow
RUN pip install -r /opt/airflow/src/requirements.txt
RUN pip install apache-airflow-providers-apache-spark